export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const AGREGAR_PRODUCTO_EXITOSO = 'AGREGAR_PRODUCTO_EXITOSO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS'
export const COMENZAR_DESCARGA_EXITOSO= 'COMENZAR_DESCARGA_EXITOSO'
export const COMENZAR_DESCARGA_ERROR = 'COMENZAR_DESCARGA_ERROR'

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR'
export const ELIMINAR_PRODUCTO_EXITOSO = 'ELIMINAR_PRODUCTO_EXITOSO'
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR'

export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR'
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO'
export const EDITAR_PRODUCTO_EXITOSO = 'EDITAR_PRODUCTO_EXITOSO'
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR'


export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'